import json
import networkx as nx

# Load the JSON file generated by pydeps
with open("dependencies.json", "r") as file:
    dependencies = json.load(file)

# Initialize graph and dependency metrics
G = nx.DiGraph()
fan_in = {module: 0 for module in dependencies}
fan_out = {module: len(dependencies[module].get("imports", [])) for module in dependencies}

# Build dependency graph
for module, data in dependencies.items():
    for imported_module in data.get("imports", []):
        G.add_edge(module, imported_module)
        if imported_module in fan_in:
            fan_in[imported_module] += 1

# Open a file to write the outputs
with open("analysis_output.txt", "w") as output_file:

    # 1️⃣ Identify Highly Coupled Modules
    highly_coupled_threshold = max(2, len(dependencies) // 10)  # Dynamic threshold
    highly_coupled = {mod for mod in dependencies if fan_in[mod] > highly_coupled_threshold or fan_out[mod] > highly_coupled_threshold}

    output_file.write("\n=== Highly Coupled Modules and Their Dependencies ===\n")
    if highly_coupled:
        for mod in highly_coupled:
            output_file.write(f"{mod}: Fan-In = {fan_in[mod]}, Fan-Out = {fan_out[mod]}\n")
            output_file.write(f"  Depends on: {dependencies[mod].get('imports', [])}\n")
            # Print the modules that depend on this module
            dependent_modules = [m for m, data in dependencies.items() if mod in data.get("imports", [])]
            output_file.write(f"  Depended on by: {dependent_modules}\n")
    else:
        output_file.write("No highly coupled modules found.\n")

    # 2️⃣ Cyclic Dependencies Detection
    output_file.write("\n=== Cyclic Dependencies (Detailed) ===\n")
    try:
        all_cycles = list(nx.simple_cycles(G))
        if all_cycles:
            for cycle in all_cycles:
                output_file.write(" -> ".join(cycle) + "\n")
        else:
            output_file.write("No cyclic dependencies found.\n")
    except Exception as e:
        output_file.write(f"Error detecting cyclic dependencies: {e}\n")

    # 3️⃣ Check for Unused and Disconnected Modules
    unused_modules = [mod for mod in dependencies if fan_in[mod] == 0]
    disconnected_modules = [mod for mod in dependencies if fan_in[mod] == 0 and fan_out[mod] == 0]

    output_file.write("\n=== Unused Modules ===\n")
    if unused_modules:
        output_file.write("\n".join(unused_modules) + "\n")
    else:
        output_file.write("No unused modules found.\n")

    output_file.write("\n=== Disconnected Modules ===\n")
    if disconnected_modules:
        output_file.write("\n".join(disconnected_modules) + "\n")
    else:
        output_file.write("No disconnected modules found.\n")

    # 4️⃣ Assess Depth of Dependencies
    output_file.write("\n=== Dependency Depth Analysis (Detailed) ===\n")
    dependency_depths = {}

    for module in dependencies:
        try:
            # Calculate the longest path from the current module to any other module
            longest_path = max(
                (nx.shortest_path_length(G, module, target) for target in G.nodes if nx.has_path(G, module, target)),
                default=0
            )
            dependency_depths[module] = longest_path
        except Exception as e:
            output_file.write(f"Error calculating depth for module {module}: {e}\n")
            dependency_depths[module] = 0

    # Print depth for all modules
    for mod, depth in dependency_depths.items():
        output_file.write(f"{mod}: Depth = {depth}\n")

    # Identify the module with the maximum depth
    max_depth_module = max(dependency_depths, key=dependency_depths.get)
    output_file.write(f"\nDeepest dependency chain starts from: {max_depth_module} (Depth: {dependency_depths[max_depth_module]})\n")