import json

# Load the JSON file generated by pydeps
with open("dependencies.json", "r") as file:
    dependencies = json.load(file)

# Initialize dictionaries for fan-in and fan-out
fan_in = {module: 0 for module in dependencies}
fan_out = {module: len(dependencies[module].get("imports", [])) for module in dependencies}

# Compute fan-in by checking which modules import the current module
for module, data in dependencies.items():
    for imported_module in data.get("imports", []):
        if imported_module in fan_in:
            fan_in[imported_module] += 1

# Print the results
print("Module Dependencies (Fan-In and Fan-Out):")
for module in sorted(dependencies):
    print(f"{module}: Fan-In = {fan_in[module]}, Fan-Out = {fan_out[module]}")
    # Write the results to a file
with open("fan_metrics.txt", "w") as outfile:
        outfile.write("Module Dependencies (Fan-In and Fan-Out):\n")
        for module in sorted(dependencies):
            outfile.write(f"{module}: Fan-In = {fan_in[module]}, Fan-Out = {fan_out[module]}\n")