# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.strings.strong_password as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    str_0 = "k^OYpA~~w&_WnywS4bw"
    dict_0 = {str_0: str_0, str_0: str_0, str_0: str_0, str_0: str_0}
    module_0.strong_password(dict_0, dict_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    bool_0 = True
    str_0 = "`/^#R/7#sR"
    var_0 = module_0.strong_password(bool_0, str_0)
    assert var_0 == 5
    bytes_0 = b"\x8b\xecFq\xeft\xaf\xf9m\x010\x90\x00u"
    module_0.strong_password(bytes_0, bytes_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    bool_0 = True
    module_0.strong_password(bool_0, bool_0)
