# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import collections as module_0
import algorithms.stack.switch_pairs as module_1


def test_case_0():
    counter_0 = module_0.Counter()
    var_0 = counter_0.total()
    var_1 = module_1.first_switch_pairs(counter_0)
    var_2 = module_1.first_switch_pairs(counter_0)
    var_3 = module_1.second_switch_pairs(counter_0)
    var_4 = counter_0.__iand__(var_3)
    var_5 = module_1.second_switch_pairs(counter_0)
    var_6 = module_1.first_switch_pairs(var_5)


def test_case_1():
    list_0 = []
    list_1 = [list_0]
    var_0 = module_1.first_switch_pairs(list_1)
    var_1 = module_1.second_switch_pairs(list_1)
    var_2 = module_1.second_switch_pairs(var_1)
    var_3 = module_1.first_switch_pairs(list_1)


def test_case_2():
    counter_0 = module_0.Counter()
    var_0 = counter_0.total()
    var_1 = module_1.second_switch_pairs(counter_0)
    var_2 = counter_0.__iand__(var_1)
    var_3 = module_1.second_switch_pairs(counter_0)
    var_4 = module_1.second_switch_pairs(counter_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    str_0 = "\n    idea: shoot\n    "
    module_1.second_switch_pairs(str_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    int_0 = 0
    module_1.first_switch_pairs(int_0)


@pytest.mark.xfail(strict=True)
def test_case_5():
    list_0 = []
    list_1 = [list_0, list_0]
    var_0 = module_1.first_switch_pairs(list_1)
    var_1 = module_1.second_switch_pairs(list_1)
    var_2 = module_1.first_switch_pairs(list_0)
    none_type_0 = None
    var_3 = var_2.__eq__(var_2)
    module_1.first_switch_pairs(none_type_0)
