# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.tree.binary_tree_paths as module_0


def test_case_0():
    none_type_0 = None
    var_0 = module_0.binary_tree_paths(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    bool_0 = True
    module_0.binary_tree_paths(bool_0)
