# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.strings.repeat_string as module_0


def test_case_0():
    bytes_0 = b"\xceoSC\xd3\x17\x156\x97\x9b\xb3\xdc\xcb\x15\x00\xd5\xe1\x97"
    var_0 = module_0.repeat_string(bytes_0, bytes_0)
    assert var_0 == 1


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    module_0.repeat_string(none_type_0, none_type_0)


def test_case_2():
    bytes_0 = b"\xa4"
    bytes_1 = b"b"
    tuple_0 = (bytes_1, bytes_1, bytes_1)
    var_0 = module_0.repeat_string(tuple_0, bytes_0)
    assert var_0 == -1
