# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.tree.invert_tree as module_0


def test_case_0():
    none_type_0 = None
    var_0 = module_0.reverse(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = "R,i\rdCI%A/RsP"
    module_0.reverse(str_0)
