# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.backtrack.letter_combination as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    str_0 = ""
    var_0 = module_0.letter_combinations(str_0)
    int_0 = -1668
    module_0.letter_combinations(int_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    bytes_0 = b"\xe0"
    module_0.letter_combinations(bytes_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    list_0 = []
    var_0 = module_0.letter_combinations(list_0)
    module_0.letter_combinations(var_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    str_0 = "48yQuJnBZ"
    module_0.letter_combinations(str_0)
