# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.tree.is_subtree as module_0
import collections as module_1


@pytest.mark.xfail(strict=True)
def test_case_0():
    int_0 = 108
    module_0.is_subtree(int_0, int_0)


def test_case_1():
    none_type_0 = None
    var_0 = module_0.comp(none_type_0, none_type_0)
    assert var_0 is True


@pytest.mark.xfail(strict=True)
def test_case_2():
    user_dict_0 = module_1.UserDict()
    module_0.comp(user_dict_0, user_dict_0)


def test_case_3():
    int_0 = 96
    none_type_0 = None
    var_0 = module_0.comp(int_0, none_type_0)
    assert var_0 is False
    var_1 = module_0.comp(none_type_0, int_0)
    assert var_1 is False
    dict_0 = {var_1: int_0, var_1: var_1, var_0: var_0, int_0: var_0}
    var_2 = module_0.comp(none_type_0, dict_0)
    assert var_2 is False


@pytest.mark.xfail(strict=True)
def test_case_4():
    int_0 = -2664
    none_type_0 = None
    var_0 = module_0.comp(int_0, none_type_0)
    assert var_0 is False
    var_0.__ior__(var_0)
