# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.arrays.rotate as module_0


def test_case_0():
    bool_0 = False
    complex_0 = 3860.79 + 816j
    list_0 = [bool_0, bool_0, complex_0, complex_0]
    var_0 = module_0.rotate_v1(list_0, bool_0)
    var_1 = module_0.rotate_v2(var_0, bool_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    var_0 = module_0.rotate_v3(none_type_0, none_type_0)
    var_1 = module_0.rotate_v3(none_type_0, none_type_0)
    var_2 = module_0.rotate_v3(var_1, none_type_0)
    module_0.rotate_v1(var_2, var_2)


@pytest.mark.xfail(strict=True)
def test_case_2():
    bool_0 = False
    complex_0 = 3860.79 + 816j
    list_0 = [bool_0, bool_0, complex_0, complex_0]
    var_0 = module_0.rotate_v1(list_0, bool_0)
    module_0.rotate_v3(list_0, var_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    none_type_0 = None
    bool_0 = False
    module_0.rotate_v1(none_type_0, bool_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    none_type_0 = None
    int_0 = -24
    module_0.rotate_v2(none_type_0, int_0)


@pytest.mark.xfail(strict=True)
def test_case_5():
    bool_0 = True
    complex_0 = 3894.275548564908 + 816j
    list_0 = [bool_0, bool_0, complex_0, complex_0]
    var_0 = module_0.rotate_v1(list_0, bool_0)
    module_0.rotate_v2(bool_0, var_0)
