# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.sort.selection_sort as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    str_0 = "A\rXk7nY2rh"
    module_0.selection_sort(str_0, str_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    int_0 = -1897
    set_0 = set()
    var_0 = module_0.selection_sort(set_0, set_0)
    module_0.selection_sort(int_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    int_0 = -1968
    module_0.selection_sort(int_0)


def test_case_3():
    float_0 = -1743.3525
    list_0 = [float_0, float_0, float_0]
    list_1 = [list_0]
    var_0 = module_0.selection_sort(list_1)


def test_case_4():
    bytes_0 = b"\x81\xdevY\xd7\xb2\xe7\xc6\xf7\x9b\xbe\xf2"
    list_0 = [bytes_0]
    var_0 = module_0.selection_sort(list_0, list_0)
    float_0 = -1743.3525
    list_1 = [float_0, float_0, float_0]
    list_2 = [list_1]
    var_1 = module_0.selection_sort(list_2)
