# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.arrays.garage as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    none_type_0 = None
    str_0 = "0I-vV;"
    var_0 = module_0.garage(str_0, str_0)
    module_0.garage(var_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    module_0.garage(none_type_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    bool_0 = False
    dict_0 = {bool_0: bool_0, bool_0: bool_0, bool_0: bool_0, bool_0: bool_0}
    list_0 = [bool_0, dict_0]
    var_0 = module_0.garage(list_0, list_0)
    module_0.garage(var_0, list_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    bool_0 = False
    dict_0 = {bool_0: bool_0, bool_0: bool_0, bool_0: bool_0, bool_0: bool_0}
    list_0 = [bool_0, dict_0]
    var_0 = module_0.garage(list_0, list_0)
    module_0.garage(list_0, var_0)
