# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.tree.longest_consecutive as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    none_type_0 = None
    var_0 = module_0.longest_consecutive(none_type_0)
    assert var_0 == 0
    var_1 = module_0.dfs(none_type_0, none_type_0, none_type_0, none_type_0)
    module_0.dfs(var_0, var_0, var_0, var_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    int_0 = -1763
    module_0.longest_consecutive(int_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    str_0 = "Key %s not found"
    str_1 = "\r\\Jv!BS"
    none_type_0 = None
    module_0.dfs(str_0, str_1, str_1, none_type_0)
