# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.tree.same_tree as module_0


def test_case_0():
    none_type_0 = None
    int_0 = 27
    var_0 = module_0.is_same_tree(none_type_0, int_0)
    assert var_0 is False


@pytest.mark.xfail(strict=True)
def test_case_1():
    int_0 = 1633
    module_0.is_same_tree(int_0, int_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    none_type_0 = None
    var_0 = module_0.is_same_tree(none_type_0, none_type_0)
    assert var_0 is True
    var_1 = module_0.is_same_tree(var_0, none_type_0)
    assert var_1 is False
    module_0.is_same_tree(var_0, var_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    int_0 = 195
    none_type_0 = None
    var_0 = module_0.is_same_tree(int_0, none_type_0)
    assert var_0 is False
    module_0.is_same_tree(int_0, var_0)
