# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.arrays.three_sum as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    str_0 = "P5d6(nrmV7"
    list_0 = [str_0, str_0, str_0]
    module_0.three_sum(list_0)


def test_case_1():
    int_0 = 3459
    list_0 = [int_0, int_0, int_0, int_0]
    var_0 = module_0.three_sum(list_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    int_0 = -879
    module_0.three_sum(int_0)


def test_case_3():
    int_0 = -575
    list_0 = [int_0, int_0, int_0, int_0, int_0, int_0, int_0]
    var_0 = module_0.three_sum(list_0)


def test_case_4():
    int_0 = 0
    list_0 = [int_0, int_0, int_0, int_0]
    var_0 = module_0.three_sum(list_0)


@pytest.mark.xfail(strict=True)
def test_case_5():
    bool_0 = False
    int_0 = -830
    list_0 = [bool_0, bool_0, bool_0, int_0]
    var_0 = module_0.three_sum(list_0)
    int_1 = 33
    module_0.three_sum(int_1)
