# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.strings.reverse_vowel as module_0


def test_case_0():
    str_0 = "p["
    var_0 = module_0.reverse_vowel(str_0)
    assert var_0 == "p["


@pytest.mark.xfail(strict=True)
def test_case_1():
    bool_0 = True
    dict_0 = {bool_0: bool_0}
    module_0.reverse_vowel(dict_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    float_0 = -1782.948
    module_0.reverse_vowel(float_0)


def test_case_3():
    str_0 = "\n    A simple implementation\n    of a polynomial class that\n    records the details about two polynomials\n    that are potentially comprised of multiple\n    variables.\n    "
    var_0 = module_0.reverse_vowel(str_0)
    assert (
        var_0
        == "\n    e sampli amplemintutoen\n    if o palynimeol cless that\n    racards thi dotools uboat twi palynemeols\n    thet ara patintoolly camprosod if malteple\n    vireiblAs.\n    "
    )


def test_case_4():
    str_0 = "ed"
    var_0 = module_0.reverse_vowel(str_0)
    assert var_0 == "ed"
