# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.tree.is_symmetric as module_0


def test_case_0():
    none_type_0 = None
    var_0 = module_0.is_symmetric(none_type_0)
    assert var_0 is True
    var_1 = module_0.helper(none_type_0, var_0)
    assert var_1 is False


@pytest.mark.xfail(strict=True)
def test_case_1():
    int_0 = 1069
    var_0 = module_0.helper(int_0, int_0)
    assert var_0 is False
    module_0.is_symmetric(int_0)


def test_case_2():
    none_type_0 = None
    var_0 = module_0.helper(none_type_0, none_type_0)
    assert var_0 is True


def test_case_3():
    bytes_0 = b""
    var_0 = module_0.helper(bytes_0, bytes_0)
    assert var_0 is False


@pytest.mark.xfail(strict=True)
def test_case_4():
    none_type_0 = None
    var_0 = module_0.is_symmetric_iterative(none_type_0)
    assert var_0 is True
    module_0.is_symmetric_iterative(var_0)


@pytest.mark.xfail(strict=True)
def test_case_5():
    set_0 = set()
    list_0 = [set_0]
    module_0.is_symmetric_iterative(list_0)
