# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.tree.path_sum2 as module_0


def test_case_0():
    none_type_0 = None
    var_0 = module_0.path_sum(none_type_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    int_0 = -2758
    module_0.path_sum(int_0, int_0)


def test_case_2():
    none_type_0 = None
    var_0 = module_0.path_sum2(none_type_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    bool_0 = True
    module_0.path_sum2(bool_0, bool_0)


def test_case_4():
    none_type_0 = None
    var_0 = module_0.path_sum3(none_type_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_5():
    bool_0 = False
    module_0.path_sum3(bool_0, bool_0)
