# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.tree.is_balanced as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    none_type_0 = None
    var_0 = module_0.is_balanced(none_type_0)
    assert var_0 is True
    module_0.is_balanced(var_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    set_0 = set()
    module_0.is_balanced(set_0)
