# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.sort.radix_sort as module_0
import builtins as module_1


@pytest.mark.xfail(strict=True)
def test_case_0():
    bytes_0 = b"n\x05,\xa6\xa8\xfb\x0c\xc6\xef\xc0\xd1n\x992\xf3\xb0\x8e"
    module_0.radix_sort(bytes_0)


def test_case_1():
    bool_0 = False
    set_0 = {bool_0}
    var_0 = module_0.radix_sort(set_0)
    var_1 = module_0.radix_sort(var_0, var_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    set_0 = set()
    module_0.radix_sort(set_0, set_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    bool_0 = True
    set_0 = {bool_0}
    module_0.radix_sort(set_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    int_0 = 4341
    list_0 = [int_0, int_0]
    var_0 = module_0.radix_sort(list_0, int_0)
    var_1 = module_0.radix_sort(list_0)
    var_2 = module_1.object()
    module_0.radix_sort(var_2)
