# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.strings.knuth_morris_pratt as module_0


def test_case_0():
    bytes_0 = b"\x8b\xac\xfeu\x04\x06I\xb7\xce\xdd*\xa5\\\xdb\x18\xee\x93\x01\xc7"
    list_0 = module_0.knuth_morris_pratt(bytes_0, bytes_0)


def test_case_1():
    set_0 = set()
    list_0 = module_0.knuth_morris_pratt(set_0, set_0)


def test_case_2():
    str_0 = "F)"
    str_1 = '/8aOvtB<"5Vfyo3c'
    list_0 = [str_0, str_0, str_0, str_1, str_1]
    list_1 = module_0.knuth_morris_pratt(list_0, list_0)


def test_case_3():
    str_0 = "H+l\t"
    str_1 = "in3H7!`\t"
    list_0 = module_0.knuth_morris_pratt(str_1, str_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    int_0 = 2545
    list_0 = [int_0, int_0, int_0, int_0]
    bool_0 = True
    list_1 = [int_0, int_0, bool_0]
    list_2 = module_0.knuth_morris_pratt(list_1, list_0)
    none_type_0 = None
    module_0.knuth_morris_pratt(list_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_5():
    int_0 = 2545
    float_0 = 2544.99
    list_0 = [int_0, int_0, int_0, float_0]
    str_0 = "7y\x0c\t"
    bool_0 = False
    list_1 = [bool_0, int_0, int_0, int_0, int_0, bool_0]
    list_2 = module_0.knuth_morris_pratt(list_1, list_0)
    module_0.knuth_morris_pratt(float_0, str_0)


def test_case_6():
    int_0 = 2545
    float_0 = 2544.99
    list_0 = [int_0, int_0, float_0, int_0, int_0, int_0, float_0]
    bool_0 = True
    list_1 = [bool_0, bool_0, int_0, int_0, bool_0]
    list_2 = module_0.knuth_morris_pratt(list_1, list_0)
    bytes_0 = b"\xdc\xb1\xabO\xc6\xad\xc40{\xa7\x99\xa5\x85 \x06\x99\x12Co]"
    list_3 = [bool_0, bytes_0]
    list_4 = module_0.knuth_morris_pratt(list_3, list_3)
