# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.arrays.summarize_ranges as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    int_0 = 1930
    list_0 = [int_0]
    list_1 = module_0.summarize_ranges(list_0)
    list_2 = module_0.summarize_ranges(list_1)
    list_3 = []
    module_0.summarize_ranges(list_3)


def test_case_1():
    bool_0 = True
    int_0 = -1758
    list_0 = [int_0, bool_0]
    list_1 = module_0.summarize_ranges(list_0)
    list_2 = [bool_0, bool_0]
    list_3 = module_0.summarize_ranges(list_2)


@pytest.mark.xfail(strict=True)
def test_case_2():
    int_0 = -485
    module_0.summarize_ranges(int_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    bool_0 = False
    bool_1 = True
    list_0 = [bool_0, bool_1]
    list_1 = module_0.summarize_ranges(list_0)
    list_2 = []
    module_0.summarize_ranges(list_2)


@pytest.mark.xfail(strict=True)
def test_case_4():
    bool_0 = False
    bool_1 = True
    list_0 = [bool_0, bool_1, bool_0, bool_0]
    list_1 = module_0.summarize_ranges(list_0)
    module_0.summarize_ranges(bool_0)
