# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.backtrack.add_operators as module_0
import builtins as module_1


@pytest.mark.xfail(strict=True)
def test_case_0():
    bytes_0 = b"a\xd6"
    module_0.add_operators(bytes_0, bytes_0)


def test_case_1():
    dict_0 = {}
    var_0 = module_0.add_operators(dict_0, dict_0)
    var_1 = module_0.add_operators(dict_0, dict_0)
    var_2 = module_0.add_operators(dict_0, dict_0)
    var_3 = module_0.add_operators(var_1, dict_0)


def test_case_2():
    str_0 = "54"
    var_0 = module_0.add_operators(str_0, str_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    float_0 = 3.0
    str_0 = "557"
    var_0 = module_0.add_operators(str_0, float_0)
    module_0.add_operators(var_0, var_0)


def test_case_4():
    float_0 = 3.0
    list_0 = []
    str_0 = "0554"
    var_0 = module_0.add_operators(str_0, float_0)
    var_1 = module_0.add_operators(var_0, list_0)
    object_0 = module_1.object()
    none_type_0 = None
    var_2 = module_0.add_operators(list_0, none_type_0)
