# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.strings.roman_to_int as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    none_type_0 = None
    module_0.roman_to_int(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = "algorithms.strings.roman_to_int"
    module_0.roman_to_int(str_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    str_0 = "h"
    module_0.roman_to_int(str_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    str_0 = "XLX_`F~"
    module_0.roman_to_int(str_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    str_0 = "XLJ~"
    module_0.roman_to_int(str_0)
