# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.strings.make_sentence as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    dict_0 = {}
    var_0 = module_0.make_sentence(dict_0, dict_0)
    bool_0 = False
    module_0.make_sentence(bool_0, bool_0)


def test_case_1():
    bytes_0 = b"\x1e\x01\x8b\xe3C,\x18\xcc5\x05?\xc1\xf9\x00}9\xb2"
    var_0 = module_0.make_sentence(bytes_0, bytes_0)
    assert var_0 is True


@pytest.mark.xfail(strict=True)
def test_case_2():
    str_0 = "eqzZ-Us@BP"
    var_0 = module_0.make_sentence(str_0, str_0)
    assert var_0 is True
    set_0 = set()
    var_1 = module_0.make_sentence(str_0, set_0)
    assert var_1 is True
    var_2 = module_0.make_sentence(str_0, set_0)
    module_0.make_sentence(var_2, str_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    bytes_0 = b"g"
    bytes_1 = b"<6\x1f%\x95\xcd\x8b"
    var_0 = module_0.make_sentence(bytes_0, bytes_0)
    assert var_0 is True
    module_0.make_sentence(bytes_0, bytes_1)
