# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.strings.multiply_strings as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    int_0 = -5086
    module_0.multiply(int_0, int_0)


def test_case_1():
    str_0 = "gsN>cfr(m6-b}V1\\Bd}"
    str_1 = module_0.multiply(str_0, str_0)
    assert str_1 == "3846443909538021488093042290219735821609"
