# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.sort.stooge_sort as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    none_type_0 = None
    module_0.stoogesort(none_type_0, none_type_0, none_type_0)


def test_case_1():
    list_0 = []
    var_0 = module_0.stoogesort(list_0, list_0, list_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    bool_0 = False
    var_0 = module_0.stoogesort(bool_0, bool_0, bool_0)
    int_0 = 484
    module_0.stoogesort(bool_0, bool_0, int_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    bool_0 = False
    bool_1 = True
    var_0 = module_0.stoogesort(bool_0, bool_1, bool_1)
    var_1 = module_0.stoogesort(bool_0, bool_0, bool_0)
    bool_2 = True
    str_0 = "R#HU#H!"
    module_0.stoogesort(str_0, bool_0, bool_2)


def test_case_4():
    bool_0 = True
    list_0 = [bool_0, bool_0, bool_0]
    bool_1 = False
    var_0 = module_0.stoogesort(list_0, bool_1, bool_0)


@pytest.mark.xfail(strict=True)
def test_case_5():
    bool_0 = False
    float_0 = 1.3
    dict_0 = {bool_0: bool_0, float_0: float_0}
    module_0.stoogesort(dict_0, bool_0, float_0)
