# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.stack.is_sorted as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bytes_0 = b"\xd9"
    module_0.is_sorted(bytes_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    list_0 = []
    var_0 = module_0.is_sorted(list_0)
    module_0.is_sorted(var_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    bool_0 = True
    module_0.is_sorted(bool_0)


def test_case_3():
    bool_0 = True
    set_0 = {bool_0, bool_0, bool_0}
    var_0 = module_0.is_sorted(set_0)
    assert var_0 is True


def test_case_4():
    bool_0 = True
    list_0 = [bool_0, bool_0]
    var_0 = module_0.is_sorted(list_0)
    assert var_0 is True


@pytest.mark.xfail(strict=True)
def test_case_5():
    int_0 = 1173
    int_1 = 0
    set_0 = {int_0, int_1, int_1, int_0}
    var_0 = module_0.is_sorted(set_0)
    assert var_0 is False
    bool_0 = False
    list_0 = [bool_0, bool_0]
    var_1 = module_0.is_sorted(list_0)
    assert var_1 is True
    module_0.is_sorted(bool_0)
