# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.sort.sort_colors as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    complex_0 = -160.82989 - 1286.713446j
    module_0.sort_colors(complex_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    bytes_0 = b"ZXt\xc4\xfd\x8b\xf6\x84\x93\xb8\x18\x85\xf4\xf8\x8c"
    module_0.sort_colors(bytes_0)


def test_case_2():
    list_0 = []
    var_0 = module_0.sort_colors(list_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    list_0 = []
    bool_0 = True
    list_1 = [bool_0, bool_0, list_0]
    module_0.sort_colors(list_1)


@pytest.mark.xfail(strict=True)
def test_case_4():
    bool_0 = False
    list_0 = [bool_0, bool_0]
    var_0 = module_0.sort_colors(list_0)
    none_type_0 = None
    module_0.sort_colors(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_5():
    int_0 = 1670
    list_0 = [int_0, int_0, int_0]
    var_0 = module_0.sort_colors(list_0)
    bool_0 = False
    module_0.sort_colors(bool_0)
