# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.stack.remove_min as module_0
import builtins as module_1


def test_case_0():
    dict_0 = {}
    var_0 = module_0.remove_min(dict_0)
    var_1 = module_0.remove_min(dict_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    bytes_0 = b"\xd1\x8a),\xfb\x07U\x88\xc8\x170\x85\xb2\x91\xae\xad"
    module_0.remove_min(bytes_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    bytes_0 = b'\xf8\xcd\xe1\xdf\xdc\x02WK\xd4"'
    list_0 = [bytes_0, bytes_0, bytes_0]
    var_0 = module_0.remove_min(list_0)
    str_0 = "Wp}\nvg"
    dict_0 = {str_0: str_0, str_0: str_0, str_0: str_0}
    module_1.object(**dict_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    float_0 = 2168.119
    bool_0 = True
    list_0 = [float_0, float_0, float_0, bool_0]
    var_0 = module_0.remove_min(list_0)
    module_0.remove_min(bool_0)
