# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.backtrack.permute as module_0
import builtins as module_1


def test_case_0():
    str_0 = "|D"
    var_0 = module_0.permute(str_0)


def test_case_1():
    str_0 = "XA<"
    var_0 = module_0.permute_recursive(str_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    int_0 = 438
    module_0.permute_recursive(int_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    str_0 = "|D"
    var_0 = module_0.permute(str_0)
    var_1 = module_0.permute_iter(str_0)
    module_1.object(*var_1)
