# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.strings.rabin_karp as module_0


def test_case_0():
    str_0 = "."
    var_0 = module_0.rabin_karp(str_0, str_0)
    assert var_0 == 0


def test_case_1():
    str_0 = "."
    str_1 = "]kktxs/4so0n%En"
    var_0 = module_0.rabin_karp(str_0, str_1)


@pytest.mark.xfail(strict=True)
def test_case_2():
    list_0 = []
    list_1 = [list_0]
    var_0 = module_0.rabin_karp(list_1, list_0)
    str_0 = "."
    none_type_0 = None
    module_0.rabin_karp(none_type_0, str_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    str_0 = "."
    tuple_0 = ()
    var_0 = module_0.rabin_karp(tuple_0, str_0)
    var_0.window_text()


@pytest.mark.xfail(strict=True)
def test_case_4():
    str_0 = ""
    none_type_0 = None
    var_0 = module_0.rabin_karp(none_type_0, str_0)
    var_1 = module_0.rabin_karp(str_0, str_0)
    var_1.window_text()
