# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.sort.wiggle_sort as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    int_0 = -1181
    module_0.wiggle_sort(int_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = "f?\n%Jt;(J]p_8'"
    module_0.wiggle_sort(str_0)


def test_case_2():
    tuple_0 = ()
    var_0 = module_0.wiggle_sort(tuple_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    str_0 = "algorthms.sort.wiggle_sort"
    module_0.wiggle_sort(str_0)
