# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.automata.dfa as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    list_0 = []
    dict_0 = module_0.DFA(list_0, list_0, list_0, list_0)
    str_0 = "|O5OnKr0V>ZHdJ*"
    module_0.DFA(str_0, str_0, str_0, str_0)


def test_case_1():
    dict_0 = {}
    var_0 = module_0.DFA(dict_0, dict_0, dict_0, dict_0)


def test_case_2():
    list_0 = []
    str_0 = "|O5OnKr0V>ZdJ*"
    var_0 = module_0.DFA(list_0, str_0, str_0, list_0)
    assert var_0 is False


def test_case_3():
    list_0 = []
    var_0 = module_0.DFA(list_0, list_0, list_0, list_0)
    str_0 = '}\\"M+)+PZBU'
    dict_0 = {var_0: list_0, var_0: var_0, var_0: var_0}
    var_1 = module_0.DFA(str_0, var_0, str_0, dict_0)
    assert var_1 is True
